# Join Statements - Lab

## Introduction

In this lab, you'll practice your knowledge of join statements, using various types of joins and various methods for specifying the links between them.

## Objectives

You will be able to:
- Write queries that make use of various types of Joins
- Join tables using foreign keys

## CRM Schema

In almost all cases, rather then just working with a single table you will typically need data from multiple tables. 
Doing this requires the use of **joins ** using shared columns from the two tables. 

In this lab, you'll use the same Customer Relationship Management (CRM) database that you saw from the previous lesson.
<img src='images/Database-Schema.png' width="600">

## Connecting to the Database
Import the necessary packages and connect to the database **data.sqlite**.

In [8]:
#Your code here
import sqlite3
import pandas as pd
conn = sqlite3.connect('data.sqlite', detect_types=sqlite3.PARSE_COLNAMES)
cur = conn.cursor()

## Display the names of all the employees in Boston.
Hint: join the employees and customers tables.

In [9]:
#Your code here
cur.execute("""select firstName, lastName from employees join offices using(officeCode) where city = 'Boston';""")
cur.fetchall()

[('Julie', 'Firrelli'), ('Steve', 'Patterson')]

## Do any offices have no employees?
Hint: Combine the employees and offices tables and use a group by.

In [10]:
#Your code here
cur.execute("""select officeCode, count(officeCode) from employees 
                      join offices using (officeCode)
                      group by officeCode""")
df = pd.DataFrame(cur.fetchall())
df

   0  1
0  1  6
1  2  2
2  3  2
3  4  5
4  5  2
5  6  4
6  7  2

In [11]:
# No!

## Write 3 Questions of your own and answer them

In [12]:
# What is the average discount of each item?

cur.execute("""select productCode as product, count(productCode) as sales_num,
                      sum(MSRP) - sum(buyprice) as discount_per_item,
                      (sum(MSRP) - sum(buyprice)) / count(productCode) as average_discount
                      from products 
                      join orderdetails using (productCode)
                      group by productCode""")

df = pd.DataFrame(cur.fetchall())
df. columns = [i[0] for i in cur.description]
df

       product  sales_num  discount_per_item  average_discount
0     S10_1678         28            1312.92             46.89
1     S10_1949         28            3240.16            115.72
2     S10_2016         28            1398.60             49.95
3     S10_4698         28            2873.92            102.64
4     S10_4757         28            1408.96             50.32
5     S10_4962         28            1240.96             44.32
6     S12_1099         27            2679.21             99.23
7     S12_1108         27            3029.67            112.21
8     S12_1666         28            1645.56             58.77
9     S12_2823         28            2361.80             84.35
10    S12_3148         27            1672.38             61.94
11    S12_3380         27            1141.56             42.28
12    S12_3891         27            2429.19             89.97
13    S12_3990         27            1292.76             47.88
14    S12_4473         28            1758.40             62.80
15    S12_4675         27            1523.61             56.43
16    S18_1097         28            1633.52             58.34
17    S18_1129         27            1566.81             58.03
18    S18_1342         28            1179.36             42.12
19    S18_1367         28             830.20             29.65
20    S18_1589         25            1462.00             58.48
21    S18_1662         28            2251.76             80.42
22    S18_1749         25            2082.50             83.30
23    S18_1889         27             623.70             23.10
24    S18_1984         27            1305.72             48.36
25    S18_2238         28            1742.16             62.22
26    S18_2248         25             681.00             27.24
27    S18_2319         28            1340.36             47.87
28    S18_2325         28            1922.20             68.65
29    S18_2432         28            1003.80             35.85
..         ...        ...                ...               ...
79    S24_4048         27            1309.50             48.50
80    S24_4258         28            1118.04             39.93
81    S24_4278         28            1014.16             36.22
82    S24_4620         27            1309.77             48.51
83    S32_1268         28            1186.64             42.38
84    S32_1374         28             923.16             32.97
85    S32_2206         27             434.43             16.09
86    S32_2509         28             787.64             28.13
87    S32_3207         27             956.34             35.42
88    S32_3522         28             868.84             31.03
89    S32_4289         28            1001.56             35.77
90    S32_4485         27            1239.84             45.92
91    S50_1341         28             464.24             16.58
92    S50_1392         28            1328.88             47.46
93    S50_1514         27             569.43             21.09
94    S50_4713         27            1274.13             47.19
95   S700_1138         27             882.09             32.67
96   S700_1691         28            1125.32             40.19
97   S700_1938         27            1169.37             43.31
98   S700_2047         28            1419.32             50.69
99   S700_2466         28             865.76             30.92
100  S700_2610         27            1034.37             38.31
101  S700_2824         28            1529.36             54.62
102  S700_2834         28            1660.96             59.32
103  S700_3167         28             716.80             25.60
104  S700_3505         27            1325.16             49.08
105  S700_3962         27            1233.36             45.68
106  S700_4002         28            1057.28             37.76
107   S72_1253         28             472.92             16.89
108   S72_3212         27             575.10             21.30

[109 rows x 4 columns]

In [98]:
# Your code here
cur.execute("""select *, sum(amount) as paid
                      from payments join customers
                      group by customers.creditLimit
                      order by customerName""")

df = pd.DataFrame(cur.fetchall())
df. columns = [i[0] for i in cur.description]
df

,customerNumber,checkNumber,paymentDate,amount,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit,paid
0,496,MN89921,2004-12-31,52166.00,187,"AV Stores, Co.",Ashworth,Rachel,(171) 555-1555,Fauntleroy Circus,,Manchester,,EC2 5NT,UK,1501,136800.00,8.853839e+06
1,496,MN89921,2004-12-31,52166.00,242,Alpha Cognac,Roulet,Annette,61.77.6555,1 rue Alsace-Lorraine,,Toulouse,,31000,France,1370,61100.00,8.853839e+06
2,496,MN89921,2004-12-31,52166.00,249,Amica Models & Co.,Accorti,Paolo,011-4988555,Via Monte Bianco 34,,Torino,,10100,Italy,1401,113000.00,8.853839e+06
3,496,MN89921,2004-12-31,52166.00,276,"Anna's Decorations, Ltd",O'Hara,Anna,02 9936 8555,201 Miller Street,Level 15,North Sydney,NSW,2060,Australia,1611,107800.00,8.853839e+06
4,496,MN89921,2004-12-31,52166.00,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",,Nantes,,44000,France,1370,21000.00,8.853839e+06
5,496,MN89921,2004-12-31,52166.00,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611,117300.00,8.853839e+06
6,496,MN89921,2004-12-31,52166.00,333,"Australian Gift Network, Co",Calaghan,Ben,61-7-3844-6555,31 Duncan St. West End,,South Brisbane,Queensland,4101,Australia,1611,51600.00,8.853839e+06
7,496,MN89921,2004-12-31,52166.00,256,Auto Associés & Cie.,Tonini,Daniel,30.59.8555,"67, avenue de l'Europe",,Versailles,,78000,France,1370,77900.00,8.853839e+06
8,496,MN89921,2004-12-31,52166.00,406,Auto Canal+ Petit,Perrier,Dominique,(1) 47.55.6555,"25, rue Lauriston",,Paris,,75016,France,1337,95000.00,8.853839e+06
9,496,MN89921,2004-12-31,52166.00,198,Auto-Moto Classics Inc.,Taylor,Leslie,6175558428,16780 Pompton St.,,Brickhaven,MA,58339,USA,1216,23000.00,8.853839e+06
10,496,MN89921,2004-12-31,52166.00,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,,Stavern,,4110,Norway,1504,81700.00,8.853839e+06
11,496,MN89921,2004-12-31,52166.00,415,"Bavarian Collectables Imports, Co.",Donnermeyer,Michael,+49 89 61 08 9555,Hansastr. 15,,Munich,,80686,Germany,1504,77000.00,1.770768e+07
12,496,MN89921,2004-12-31,52166.00,128,"Blauer See Auto, Co.",Keitel,Roland,+49 69 66 90 2555,Lyonerstr. 34,,Frankfurt,,60528,Germany,1504,59700.00,8.853839e+06
13,496,MN89921,2004-12-31,52166.00,219,Boards & Toys Co.,Young,Mary,3105552373,4097 Douglas Av.,,Glendale,CA,92561,USA,1166,11000.00,8.853839e+06
14,496,MN89921,2004-12-31,52166.00,344,CAF Imports,Fernandez,Jesus,+34 913 728 555,Merchants House,27-30 Merchant's Quay,Madrid,,28023,Spain,1702,59600.00,8.853839e+06
15,496,MN89921,2004-12-31,52166.00,173,Cambridge Collectables Co.,Tseng,Jerry,6175555555,4658 Baden Av.,,Cambridge,MA,51247,USA,1188,43400.00,8.853839e+06
16,496,MN89921,2004-12-31,52166.00,202,Canadian Gift Exchange Network,Tamuri,Yoshi,(604) 555-3392,1900 Oak St.,,Vancouver,BC,V3F 2K1,Canada,1323,90300.00,8.853839e+06
17,496,MN89921,2004-12-31,52166.00,424,Classic Legends Inc.,Hernandez,Maria,2125558493,5905 Pompton St.,Suite 750,NYC,NY,10022,USA,1286,67500.00,8.853839e+06
18,496,MN89921,2004-12-31,52166.00,189,"Clover Collections, Co.",Cassidy,Dean,+353 1862 1555,25 Maiden Lane,Floor No. 4,Dublin,,2,Ireland,1504,69400.00,8.853839e+06
19,496,MN89921,2004-12-31,52166.00,379,Collectables For Less Inc.,Nelson,Allen,6175558555,7825 Douglas Av.,,Brickhaven,MA,58339,USA,1188,70700.00,8.853839e+06
20,496,MN89921,2004-12-31,52166.00,321,Corporate Gift Ideas Co.,Brown,Julie,6505551386,7734 Strong St.,,San Francisco,CA,94217,USA,1165,105000.00,1.770768e+07
21,496,MN89921,2004-12-31,52166.00,458,"Corrida Auto Replicas, Ltd",Sommer,Martín,(91) 555 22 82,"C/ Araquil, 67",,Madrid,,28023,Spain,1702,104600.00,8.853839e+06
22,496,MN89921,2004-12-31,52166.00,385,Cruz & Sons Co.,Cruz,Arnold,+63 2 555 3587,15 McCallum Street,NatWest Center #13-03,Makati City,,1227 MM,Philippines,1621,81500.00,8.853839e+06
23,496,MN89921,2004-12-31,52166.00,171,Daedalus Designs Imports,Rancé,Martine,20.16.1555,"184, chaussée de Tournai",,Lille,,59000,France,1370,82900.00,8.853839e+06
24,496,MN89921,2004-12-31,52166.00,145,Danish Wholesale Imports,Petersen,Jytte,31 12 3555,Vinbæltet 34,,Kobenhavn,,1734,Denmark,1401,83400.00,8.853839e+06
25,496,MN89921,2004-12-31,52166.00,157,Diecast Classics Inc.,Leong,Kelvin,2155551555,7586 Pompton St.,,Allentown,PA,70267,USA,1216,100600.00,8.853839e+06
26,496,MN89921,2004-12-31,52166.00,495,Diecast Collectables,Franco,Valarie,6175552555,6251 Ingle Ln.,,Boston,MA,51003,USA,1188,85100.00,8.853839e+06
27,496,MN89921,2004-12-31,52166.00,489,"Double Decker Gift Stores, Ltd",Smith,Thomas,(171) 555-7555,120 Hanover Sq.,,London,,WA1 1DP,UK,1501,43300.00,8.853839e+06
28,496,MN89921,2004-12-31,52166.00,323,"Down Under Souveniers, Inc",Graham,Mike,+64 9 312 5555,162-164 Grafton Road,Level 2,Auckland,,,New Zealand,1612,88000.00,8.853839e+06
29,496,MN89921,2004-12-31,52166.00,148,"Dragon Souveniers, Ltd.",Natividad,Eric,+65 221 7555,Bronz Sok.,Bronz Apt. 3/6 Tesvikiye,Singapore,,079903,Singapore,1621,103800.00,8.853839e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,496,MN89921,2004-12-31,52166.00,177,Osaka Souveniers Co.,Kentary,Mory,+81 06 6342 5555,1-6-20 Dojima,,Kita-ku,Osaka,530-0003,Japan,1621,81200.00,8.853839e+06
64,496,MN89921,2004-12-31,52166.00,311,"Oulu Toy Supplies, Inc.",Koskitalo,Pirkko,981-443655,Torikatu 38,,Oulu,,90110,Finland,1501,90500.00,8.853839e+06
65,496,MN89921,2004-12-31,52166.00,314,Petit Auto,Dewey,Catherine,(02) 5554 67,Rue Joseph-Bens 532,,Bruxelles,,B-1180,Belgium,1401,79900.00,8.853839e+06
66,496,MN89921,2004-12-31,52166.00,233,Québec Home Shopping Network,Fresnière,Jean,(514) 555-8054,43 rue St. Laurent,,Montréal,Québec,H1J 1C3,Canada,1286,48700.00,8.853839e+06
67,496,MN89921,2004-12-31,52166.00,481,"Raanan Stores, Inc","Altagar,G M",Raanan,+ 972 9 959 8555,3 Hagalim Blv.,,Herzlia,,47625,Israel,,0.00,2.124921e+08
68,496,MN89921,2004-12-31,52166.00,353,Reims Collectables,Henriot,Paul,26.47.1555,59 rue de l'Abbaye,,Reims,,51100,France,1337,81100.00,1.770768e+07
69,496,MN89921,2004-12-31,52166.00,278,Rovelli Gifts,Rovelli,Giovanni,035-640555,Via Ludovico il Moro 22,,Bergamo,,24100,Italy,1401,119600.00,8.853839e+06
70,496,MN89921,2004-12-31,52166.00,260,"Royal Canadian Collectables, Ltd.",Lincoln,Elizabeth,(604) 555-4555,23 Tsawassen Blvd.,,Tsawassen,BC,T2F 8M4,Canada,1323,89600.00,8.853839e+06
71,496,MN89921,2004-12-31,52166.00,381,Royale Belge,Cartrain,Pascale,(071) 23 67 2555,"Boulevard Tirou, 255",,Charleroi,,B-6000,Belgium,1401,23500.00,8.853839e+06
72,496,MN89921,2004-12-31,52166.00,382,Salzburg Collectables,Pipps,Georg,6562-9555,Geislweg 14,,Salzburg,,5020,Austria,1401,71700.00,8.853839e+06
73,496,MN89921,2004-12-31,52166.00,146,"Saveley & Henriot, Co.",Saveley,Mary,78.32.5555,"2, rue du Commerce",,Lyon,,69004,France,1337,123900.00,8.853839e+06
74,496,MN89921,2004-12-31,52166.00,448,Scandinavian Gift Ideas,Larsson,Martha,0695-34 6555,Åkergatan 24,,Bräcke,,S-844 67,Sweden,1504,116400.00,8.853839e+06
75,496,MN89921,2004-12-31,52166.00,487,Signal Collectibles Ltd.,Taylor,Sue,4155554312,2793 Furth Circle,,Brisbane,CA,94217,USA,1165,60300.00,2.656152e+07
76,496,MN89921,2004-12-31,52166.00,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,,Las Vegas,NV,83030,USA,1166,71800.00,8.853839e+06
77,496,MN89921,2004-12-31,52166.00,282,Souveniers And Things Co.,Huxley,Adrian,+61 2 9495 8555,Monitor Money Building,815 Pacific Hwy,Chatswood,NSW,2067,Australia,1611,93300.00,8.853839e+06
78,496,MN89921,2004-12-31,52166.00,334,Suominen Souveniers,Suominen,Kalle,+358 9 8045 555,Software Engineering Center,SEC Oy,Espoo,,FIN-02271,Finland,1501,98800.00,8.853839e+06
79,496,MN89921,2004-12-31,52166.00,455,Super Scale Inc.,Murphy,Leslie,2035559545,567 North Pendale Street,,New Haven,CT,97823,USA,1286,95400.00,8.853839e+06
80,496,MN89921,2004-12-31,52166.00,161,Technics Stores Inc.,Hashimoto,Juri,6505556809,9408 Furth Circle,,Burlingame,CA,94217,USA,1165,84600.00,8.853839e+06
81,496,MN89921,2004-12-31,52166.00,328,Tekni Collectables Inc.,Brown,William,2015559350,7476 Moss Rd.,,Newark,NJ,94019,USA,1323,43000.00,8.853839e+06
82,496,MN89921,2004-12-31,52166.00,450,The Sharp Gifts Warehouse,Frick,Sue,4085553659,3086 Ingle Ln.,,San Jose,CA,94217,USA,1165,77600.00,8.853839e+06
83,496,MN89921,2004-12-31,52166.00,398,"Tokyo Collectables, Ltd",Shimamura,Akiko,+81 3 3584 0555,2-2-8 Roppongi,,Minato-ku,Tokyo,106-0032,Japan,1621,94400.00,8.853839e+06
84,496,MN89921,2004-12-31,52166.00,259,"Toms Spezialitäten, Ltd",Pfalzheim,Henriette,0221-5554327,Mehrheimerstr. 369,,Köln,,50739,Germany,1504,120400.00,8.853839e+06
85,496,MN89921,2004-12-31,52166.00,186,"Toys of Finland, Co.",Karttunen,Matti,90-224 8555,Keskuskatu 45,,Helsinki,,21240,Finland,1501,96500.00,8.853839e+06
86,496,MN89921,2004-12-31,52166.00,205,Toys4GrownUps.com,Young,Julie,6265557265,78934 Hillside Dr.,,Pasadena,CA,90003,USA,1166,90700.00,8.853839e+06
87,496,MN89921,2004-12-31,52166.00,201,"UK Collectables, Ltd.",Devon,Elizabeth,(171) 555-2282,"12, Berkeley Gardens Blvd",,Liverpool,,WX1 6LT,UK,1501,92700.00,8.853839e+06
88,496,MN89921,2004-12-31,52166.00,298,"Vida Sport, Ltd",Holz,Mihael,0897-034555,Grenzacherweg 237,,Genève,,1203,Switzerland,1702,141300.00,8.853839e+06
89,496,MN89921,2004-12-31,52166.00,181,Vitachrome Inc.,Frick,Michael,2125551500,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,1286,76400.00,8.853839e+06
90,496,MN89921,2004-12-31,52166.00,144,"Volvo Model Replicas, Co",Berglund,Christina,0921-12 3555,Berguvsvägen 8,,Luleå,,S-958 22,Sweden,1504,53100.00,8.853839e+06
91,496,MN89921,2004-12-31,52166.00,475,West Coast Collectables Co.,Thompson,Steve,3105553722,3675 Furth Circle,,Burbank,CA,94019,USA,1166,55400.00,8.853839e+06
92,496,MN89921,2004-12-31,52166.00,240,giftsbymail.co.uk,Bennett,Helen,(198) 555-8888,Garden House,Crowther Way 23,Cowes,Isle of Wight,PO31 7PJ,UK,1501,93900.00,8.853839e+06

In [7]:
# Your code here

In [ ]:
# Your code here

## Level Up: Display the names of each product each employee has sold

In [ ]:
# Your code here

## Level Up: Display the Number of Products each employee has sold

In [ ]:
#Your code here

## Summary

Congrats! You now know how to use join statements, along with leveraging your foreign keys knowledge!